apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-test
  namespace: kube-system
data:
  # do not provision any "spare" nodes for test/staging clusters
  BUFFER_SPARE_NODES: "0"
  # allow to downscale two nodes at once
  SCALE_DOWN_STEP_FIXED: "2"
