apiVersion: v1
kind: Secret
metadata:
  name: cluster-infrastructure-secrets
  namespace: default
type: Opaque
data:
  zmon-sql-user: "{{ .ConfigItems.zmon_worker_plugin_sql_user | base64 }}"
  zmon-sql-pass: "{{ .ConfigItems.zmon_worker_plugin_sql_pass | base64 }}"
  scalyr-access-key: "{{ .ConfigItems.scalyr_access_key | base64 }}"
