apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "limits"
  namespace: cron
spec:
  limits:
    - type: "Container"
      defaultRequest:
        cpu: "100m"
        memory: 100Mi
      default:
        # cron default limit for CPU is 3 cores as we discovered that this is a sweet spot for JVM apps to startup quickly
        cpu: "3000m"
        memory: 1Gi
      max:
        cpu: "16"
        memory: 64Gi
