apiVersion: v1
kind: Secret
metadata:
  name: instana-agent
  namespace: kube-system
  labels:
    application: instana-agent
type: Opaque
data:
  instana-key: "{{ .ConfigItems.instana_key | base64 }}"
