apiVersion: v1
kind: Service
metadata:
  name: kube-dns-b
  namespace: kube-system
  labels:
    application: kube-dns-b
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeDNS"
spec:
  selector:
    application: kube-dns-b
  clusterIP: 10.3.0.11
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
