# from: ../platformcredentialsset/customresourcedefinition.yaml
# This is a hack put in place to ensure that the CustomResourceDefinition will
# be created before the actual PlatformCredentialsSet resource.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: platformcredentialssets.zalando.org
spec:
  scope: Namespaced
  group: zalando.org
  version: v1
  names:
    kind: PlatformCredentialsSet
    plural: platformcredentialssets
    singular: platformcredentialsset
    shortNames:
    - pcs

---

apiVersion: "zalando.org/v1"
kind: PlatformCredentialsSet
metadata:
   name: "audittrail-adapter"
   namespace: kube-system
   labels:
     application: "audittrail-adapter"
spec:
   application: "audittrail-adapter"
   tokens:
     audittrail:
       privileges: []
