apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: audittrail-adapter
  namespace: kube-system
  labels:
    application: audittrail-adapter
    version: v0.1.0
spec:
  replicas: 3
  selector:
    matchLabels:
      application: audittrail-adapter
  template:
    metadata:
      labels:
        application: audittrail-adapter
        version: v0.1.0
    spec:
      containers:
      - name: audittrail-adapter
        image: pierone.stups.zalan.do/teapot/audittrail-adapter:v0.1.0
        args:
        - --cluster-id={{ .ID }}
        resources:
          requests:
            memory: 32Mi
            cpu: 10m
          limits:
            memory: 128Mi
            cpu: 100m
