apiVersion: v1
kind: Service
metadata:
  name: audittrail-adapter
  namespace: kube-system
  labels:
    application: audittrail-adapter
spec:
  type: ClusterIP
  selector:
    application: audittrail-adapter
  ports:
  - port: 8080
    targetPort: 8080
